### ISSUE TITLE
Code is not go fmt'd

### ISSUE THREAD

**Issue by peterbourgon** [Qlova/seed#5]
I wasn't able to get the repo to compile on my Mac, but I'd bet you'd also find a lot of problems with `go vet` and [`staticcheck`](https://www.staticcheck.io).

**Comment by Splizard** [comment]
Cheers, I have go fmt'd the repos, nothing major from go vet or staticcheck, any details on why you couldn't get it to compile?

I have tested on Mac, Android+Termux, Windows and Linux and there all these platforms work for me.
